<?php

declare(strict_types=1);
$config=require __DIR__.'/../config/database.php';
$dsn=sprintf('mysql:host=%s;port=%s;dbname=%s;charset=%s',$config['host'],$config['port'],$config['database'],$config['charset']);
try{$pdo=new PDO($dsn,$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}catch(Throwable $e){exit('Base de données indisponible.');}
$id=(int)($_GET['product']??$_POST['product_id']??0);$product=null;if($id){$s=$pdo->prepare('SELECT id,name,sku FROM products WHERE id=?');$s->execute([$id]);$product=$s->fetch();}
$sent=false;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $company=trim($_POST['company_name']??'');$contact=trim($_POST['contact_name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$qty=max(1,(int)($_POST['quantity']??1));$message=trim($_POST['message']??'');
 if($company===''||$contact===''||!filter_var($email,FILTER_VALIDATE_EMAIL)){$error='Veuillez compléter les champs obligatoires.';}else{$s=$pdo->prepare('INSERT INTO quote_requests(company_name,contact_name,email,phone,product_id,quantity,message) VALUES(?,?,?,?,?,?,?)');$s->execute([$company,$contact,$email,$phone,$id?:null,$qty,$message]);$sent=true;}
}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Demande de devis — DistriTech</title><style>body{font-family:Arial;margin:0;background:#f5f7fa;color:#142033}.nav{background:#07111f;padding:20px 6%;color:#fff}.nav a{color:#fff;margin-left:20px;text-decoration:none}.box{max-width:700px;margin:55px auto;background:#fff;padding:32px;border-radius:14px;border:1px solid #e1e7ef}label{display:block;margin:15px 0 6px;font-weight:bold}input,textarea{width:100%;padding:12px;border:1px solid #ccd6e2;border-radius:7px;box-sizing:border-box}button{margin-top:22px;padding:13px 20px;background:#0b89ad;color:white;border:0;border-radius:7px;font-weight:bold}.ok{padding:14px;background:#e8f7ef;color:#17683d}.err{padding:14px;background:#fff0f0;color:#a12626}</style></head><body><nav class="nav"><strong>DistriTech</strong><a href="catalog.php">Catalogue</a></nav><main class="box"><h1>Demander un devis</h1><?php if($sent): ?><div class="ok">Votre demande a bien été enregistrée. Notre équipe vous contactera.</div><?php else: ?><?php if($error): ?><div class="err"><?=e($error)?></div><?php endif; ?><p>Produit : <strong><?=e($product['name']??'Solution personnalisée')?></strong></p><form method="post"><input type="hidden" name="product_id" value="<?=e($id)?>"><label>Société *</label><input name="company_name" required><label>Nom & prénom *</label><input name="contact_name" required><label>Email *</label><input type="email" name="email" required><label>Téléphone</label><input name="phone"><label>Quantité</label><input type="number" name="quantity" min="1" value="1"><label>Besoin / informations</label><textarea name="message" rows="6"></textarea><button>Envoyer la demande</button></form><?php endif; ?></main></body></html>
