<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/security.php'; secure_session_start();
require dirname(__DIR__).'/app/Database.php'; require dirname(__DIR__).'/app/helpers.php';
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $name=trim((string)($_POST['name']??'')); $company=trim((string)($_POST['company']??'')); $email=mb_strtolower(trim((string)($_POST['email']??''))); $phone=trim((string)($_POST['phone']??'')); $password=(string)($_POST['password']??'');
 if(!verify_captcha('register',(string)($_POST['captcha']??'')))$errors[]='La réponse de sécurité est incorrecte.';
 if(mb_strlen($name)<2)$errors[]='Le nom complet est obligatoire.'; if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='L’adresse e-mail est invalide.'; if(!preg_match('/^[+0-9][0-9 .()-]{7,24}$/',$phone))$errors[]='Le numéro de téléphone est invalide.'; if(strlen($password)<12)$errors[]='Le mot de passe doit contenir au moins 12 caractères.';
 if($errors===[]){$pdo=Database::connection();if(!$pdo)$errors[]='Base MySQL indisponible. Importez database/customer_migration.sql.';else{try{$s=$pdo->prepare('INSERT INTO customer_users(full_name,company,email,phone,password_hash) VALUES(:name,:company,:email,:phone,:hash)');$s->execute(['name'=>$name,'company'=>$company?:null,'email'=>$email,'phone'=>$phone,'hash'=>password_hash($password,PASSWORD_DEFAULT)]);session_regenerate_id(true);$_SESSION['customer_id']=(int)$pdo->lastInsertId();header('Location: account.php?created=1');exit;}catch(PDOException $e){$errors[]='Cette adresse e-mail possède déjà un compte.';}}}
}
$pageTitle='Créer un compte client';require __DIR__.'/partials/header.php';?>
<section class="account-page"><div class="account-card"><span class="eyebrow">ESPACE CLIENT</span><h1>Créer votre compte</h1><p>Renseignez vos coordonnées professionnelles. La vérification SMS pourra être activée ultérieurement.</p><?php foreach($errors as $error):?><div class="notice error"><?=e($error)?></div><?php endforeach;?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="two-cols"><label>Nom complet *<input name="name" required maxlength="120" value="<?=e($_POST['name']??'')?>"></label><label>Société<input name="company" maxlength="160" value="<?=e($_POST['company']??'')?>"></label></div><div class="two-cols"><label>E-mail professionnel *<input type="email" name="email" required maxlength="190" value="<?=e($_POST['email']??'')?>"></label><label>Téléphone *<input type="tel" name="phone" required maxlength="30" placeholder="+212 6 00 00 00 00" value="<?=e($_POST['phone']??'')?>"></label></div><label>Mot de passe *<input type="password" name="password" minlength="12" autocomplete="new-password" required></label><label class="captcha-field">Vérification : combien font <?=e(captcha_question('register'))?> ?<input type="number" name="captcha" required autocomplete="off"></label><button class="button primary full">Créer mon compte</button></form><p class="account-switch">Déjà client ? <a href="<?=e(url('customer-login.php'))?>">Se connecter</a></p></div></section>
<?php require __DIR__.'/partials/footer.php';?>
