<?php
require __DIR__ . '/bootstrap.php'; AdminAuth::requireLogin(); $pdo=admin_db(); $id=(int)($_GET['id']??0); $product=null;
if($id){$s=$pdo->prepare('SELECT * FROM products WHERE id=:id');$s->execute(['id'=>$id]);$product=$s->fetch();if(!$product){http_response_code(404);exit('Produit introuvable');}}
$categories=$pdo->query('SELECT id,name FROM categories WHERE active=1 ORDER BY position,name')->fetchAll(); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $data=['category_id'=>(int)$_POST['category_id'],'sku'=>trim($_POST['sku']),'name'=>trim($_POST['name']),'brand'=>trim($_POST['brand']),'version'=>trim($_POST['version']),'users_label'=>trim($_POST['users_label']),'license_type'=>trim($_POST['license_type']),'unit'=>trim($_POST['unit']),'purchase_price'=>$_POST['purchase_price']!==''?(float)$_POST['purchase_price']:null,'sale_price'=>$_POST['sale_price']!==''?(float)$_POST['sale_price']:null,'quote_only'=>isset($_POST['quote_only'])?1:0,'featured'=>isset($_POST['featured'])?1:0,'short_description'=>trim($_POST['short_description']),'active'=>isset($_POST['active'])?1:0];
 if($data['sku']===''||$data['name']===''||$data['brand']===''||$data['unit']===''||$data['short_description']==='')$error='Complétez les champs obligatoires.'; else { try { if($id){$set=implode(',',array_map(fn($k)=>"$k=:$k",array_keys($data)));$data['id']=$id;$s=$pdo->prepare("UPDATE products SET $set WHERE id=:id");}else{$cols=implode(',',array_keys($data));$vals=implode(',',array_map(fn($k)=>":$k",array_keys($data)));$s=$pdo->prepare("INSERT INTO products($cols) VALUES($vals)");}$s->execute($data);header('Location: index.php?saved=1');exit;}catch(PDOException $e){$error='SKU déjà utilisé ou données invalides.';} }
}
$v=fn($key,$default='')=>$_POST[$key]??$product[$key]??$default; admin_header($id?'Modifier le produit':'Ajouter un produit'); ?>
<div class="admin-title"><div><span class="kicker">CATALOGUE</span><h1><?= $id?'Modifier':'Ajouter' ?> un produit</h1></div><a href="index.php">← Retour</a></div><?php if($error): ?><div class="alert error"><?= e($error) ?></div><?php endif; ?><form method="post" class="product-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="form-grid"><label>Catégorie *<select name="category_id" required><?php foreach($categories as $c): ?><option value="<?= (int)$c['id'] ?>" <?= (int)$v('category_id')===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></label><label>SKU *<input name="sku" required value="<?= e((string)$v('sku')) ?>"></label><label class="wide">Nom du produit *<input name="name" required value="<?= e((string)$v('name')) ?>"></label><label>Marque *<input name="brand" required value="<?= e((string)$v('brand')) ?>"></label><label>Version<input name="version" value="<?= e((string)$v('version')) ?>"></label><label>Utilisateurs<input name="users_label" value="<?= e((string)$v('users_label')) ?>"></label><label>Type de licence<input name="license_type" value="<?= e((string)$v('license_type')) ?>"></label><label>Unité *<input name="unit" required value="<?= e((string)$v('unit')) ?>"></label><label>Prix d’achat DH<input type="number" step="0.01" min="0" name="purchase_price" value="<?= e((string)$v('purchase_price')) ?>"></label><label>Prix de vente DH<input type="number" step="0.01" min="0" name="sale_price" value="<?= e((string)$v('sale_price')) ?>"></label><label class="wide">Description *<textarea name="short_description" maxlength="255" required><?= e((string)$v('short_description')) ?></textarea></label></div><div class="checks"><label><input type="checkbox" name="quote_only" <?= $v('quote_only')?'checked':'' ?>> Sur devis</label><label><input type="checkbox" name="featured" <?= $v('featured')?'checked':'' ?>> Produit populaire</label><label><input type="checkbox" name="active" <?= $v('active',1)?'checked':'' ?>> Actif</label></div><button class="admin-button">Enregistrer</button></form><?php admin_footer(); ?>
